<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="18067" started-at="2019-07-03T15:56:45Z" finished-at="2019-07-03T15:57:03Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="18067" started-at="2019-07-03T15:56:45Z" finished-at="2019-07-03T15:57:03Z">
      <class name="com.devops.seleniumtests.SeleniumTests">
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:com.devops.seleniumtests.SeleniumTests@59fa1d9b]" name="beforeTest" is-config="true" duration-ms="7150" started-at="2019-07-03T15:56:45Z" finished-at="2019-07-03T15:56:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="FAIL" signature="login()[pri:0, instance:com.devops.seleniumtests.SeleniumTests@59fa1d9b]" name="login" duration-ms="10742" started-at="2019-07-03T15:56:53Z" finished-at="2019-07-03T15:57:03Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Find a Flight: Mercury Tours] but found [Find a Flight: Mercury Tours:]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Find a Flight: Mercury Tours] but found [Find a Flight: Mercury Tours:]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.devops.seleniumtests.SeleniumTests.login(SeleniumTests.java:30)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:com.devops.seleniumtests.SeleniumTests@59fa1d9b]" name="afterTest" is-config="true" duration-ms="115" started-at="2019-07-03T15:57:03Z" finished-at="2019-07-03T15:57:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- com.devops.seleniumtests.SeleniumTests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
